knp_paginator:
    page_range: 5                      # nombre de liens affichés dans la barre de pagination
    default_options:
        page_name: page                # nom du paramètre de page dans l'URL
        sort_field_name: sort          # nom du paramètre de tri dans l'URL
        sort_direction_name: direction # nom du paramètre de direction de tri dans l'URL
        distinct: true                 # s'assurer que les résultats sont distincts
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig' # Utilisez le modèle qui correspond à votre version de Bootstrap
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig
